language: generic

#env:
matrix:
    allow_failures:
        - env: TARGET_SYSTEM=OSX
    include:
        - os: osx
          cache: ccache
          osx_image: xcode9.4
          env: 
          - TARGET_SYSTEM=OSX
            JOBS="`sysctl -n hw.ncpu`"
            MACOSX_DEPLOYMENT_TARGET=10.8
            HOMEBREW_NO_AUTO_UPDATE=1
          before_script:
            - brew update
            - bash ./dep-install.sh
            - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
            - bash  ./upload_rotate.sh "continuous" *.tgz
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:unstable)$/
